initial commit
daily-demos/examples pull request #11
Opened 2021-06-17 14:46 UTC by jptaylor

2021-06-17 14:51 UTC, philmillman approved these changes
as long as @regexident approves, then LGTM!

2021-06-17 15:13 UTC, ablwr approved these changes

2021-06-17 15:13 UTC, ablwr commented
Yep, what Phil said

2021-06-17 18:18 UTC, regexident requested changes

2021-06-17 18:18 UTC, regexident commented on prebuilt-ui/ios-webview/ios-webview/WebViewPrebuilt/ViewController.swift
> +        // We don't intend to ever show the webview, so we give it a zero-size:
This comment is obsolete, as unlike party-line we _do_ intend to show the webview.

2021-06-17 18:18 UTC, regexident commented on prebuilt-ui/ios-webview/ios-webview/WebViewPrebuilt/ViewController.swift
> +        // Since the webview is off-screen anyway these are
This comment is obsolete, as unlike party-line the webview is _not_ off-screen.

2021-06-21 10:00 UTC, merged

2021-06-21 14:00 UTC, regexident reviewed
:+1: