Waiting participants hook
daily-demos/examples pull request #75
Opened 2022-04-04 10:26 UTC by harshithpabbati

This PR uses `useWaitingParticipants` hooks.

2022-04-07 08:14 UTC, nienkedekker approved these changes

2022-04-07 19:27 UTC, jessmitch42 commented on custom/shared/contexts/WaitingRoomProvider.js
> -  };
so much shorter 😍

2022-04-07 19:27 UTC, jessmitch42 commented on custom/shared/contexts/WaitingRoomProvider.js
> -  };
so much shorter 😍

2022-04-07 19:33 UTC, jessmitch42 requested changes
Looking good! Loving these changes split into smaller PRs. Thanks for doing that!

A couple bugs I noticed while testing: 

- clicking "Go back" doesn't seem to do anything if the room isn't valid
<img width="686" alt="CleanShot 2022-04-07 at 15 29 05@2x" src="https://user-images.githubusercontent.com/18265845/162281647-090d3f82-1fa6-4549-aa45-6b6b6b170e8a.png">

- I get the participant waiting to join notification as an owner but when I let them join I get this error on the owner and participant's end
<img width="1295" alt="CleanShot 2022-04-07 at 15 30 59@2x" src="https://user-images.githubusercontent.com/18265845/162281996-7af04498-bbe6-47d5-827b-91757f7c1ee3.png">

2022-04-11 20:37 UTC, jessmitch42 commented on custom/basic-call/pages/not-found.js
> +      <MessageCard error header="Room not found" onBack={() => router.push('/')}>
this anonymous`onBack` function can be a named function (I've given this feedback on other PRs, please use it as a general request for React demo code.)

`const returnToHomePage = () => router.push('/')`
`onBack={returnToHomePage}`

2022-04-11 20:40 UTC, jessmitch42 commented
I noticed you opened a new PR for a piece of feedback in this PR. Small request: please either link to related PRs in the PR comment where the feedback was added so I know where to look or just add the changes here. 🙏  I don't spend enough time in this repo to keep track from memory. (Your fix solved the bug, though 👍 )

2022-04-12 14:00 UTC, jessmitch42 approved these changes
Looks great!

2022-04-20 09:47 UTC, merged